name: Build and Deploy Jekyll Site

on:
  push:
    branches:
      - main  # 또는 배포하려는 브랜치 이름

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'  # Jekyll과 호환되는 Ruby 버전

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Build the site
        run: |
          bundle exec jekyll build

      - name: Deploy to GitHub Pages
        uses: actions-gh-pages@v3
        with:
          folder: _site
